# Generated by Django 3.2.3 on 2021-05-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xaccele', models.FloatField()),
                ('yaccele', models.FloatField()),
                ('zaccele', models.FloatField()),
                ('xgyro', models.FloatField()),
                ('ygyro', models.FloatField()),
                ('zgyro', models.FloatField()),
                ('timestemp', models.TimeField()),
            ],
        ),
    ]
