# Generated by Django 3.2.3 on 2021-05-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingponghit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pingponghit',
            name='data',
            field=models.JSONField(),
        ),
    ]
