# Generated by Django 3.2.3 on 2021-05-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingponghit', '0002_alter_pingponghit_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pingponghit',
            name='data',
            field=models.TextField(),
        ),
    ]
